### ISSUE TITLE
support for Nightscout token based authentication

### ISSUE THREAD

**Issue by PieterGit** [ecc1/nightscout#1]
Hi @ecc1 

It would be great if your nightscout uploader also supports token based authentication.

See https://github.com/nightscout/cgm-remote-monitor/pull/1868 and http://www.nightscout.info/wiki/welcome/website-features/0-9-features/authentication-roles

Easiest is to also a token, and supply that as a parameter at the end of the URL request (e.g. `token=devicename-hash`)

I use `AUTH_DEFAULT_ROLES=denied`  on my Nightscout instance.

**Comment by ecc1** [comment]
I'm planning to add this.  How about if I add the token to the URL if there's a ```NIGHTSCOUT_AUTH_TOKEN``` environment variable set?

**Comment by PieterGit** [comment]
Closing. Will be implemented with https://github.com/ecc1/nightscout/pull/4
